package edu.unimetsim.view;


import edu.unimetsim.model.PCB;
import edu.unimetsim.model.ProcessManager;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import edu.unimetsim.structures.LinkedList;
import edu.unimetsim.structures.Queue;
import edu.unimetsim.structures.Node;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pinto
 */
public class SimulatorWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimulatorWindow.class.getName());
    private ProcessManager kernel; //Para que se entienda con el PM

    
    public void setKernel(ProcessManager kernel) {
        this.kernel = kernel;
        refreshMissionControl();
    }
    /**
     * Creates new form SimulatorWindow
     */
    public SimulatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTabbedPanel = new javax.swing.JTabbedPane();
        pnlMissionControl = new javax.swing.JPanel();
        pnlReadyQueue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReady = new javax.swing.JTable();
        pnlRunningProcess = new javax.swing.JPanel();
        lblCpuProcess = new javax.swing.JLabel();
        barCpuProgress = new javax.swing.JProgressBar();
        lblCpuDeadline = new javax.swing.JLabel();
        pnlBlockedQueue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBlocked = new javax.swing.JTable();
        btnEmergency = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        pnlMemorySwap = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlReadyQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "READY QUEUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblReady.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane1.setViewportView(tblReady);

        javax.swing.GroupLayout pnlReadyQueueLayout = new javax.swing.GroupLayout(pnlReadyQueue);
        pnlReadyQueue.setLayout(pnlReadyQueueLayout);
        pnlReadyQueueLayout.setHorizontalGroup(
            pnlReadyQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReadyQueueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReadyQueueLayout.setVerticalGroup(
            pnlReadyQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadyQueueLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRunningProcess.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RUNNING PROCESS (CPU)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        lblCpuProcess.setText("NO PROCESS");

        lblCpuDeadline.setText("DEADLINE IN: -- CYCLES");

        javax.swing.GroupLayout pnlRunningProcessLayout = new javax.swing.GroupLayout(pnlRunningProcess);
        pnlRunningProcess.setLayout(pnlRunningProcessLayout);
        pnlRunningProcessLayout.setHorizontalGroup(
            pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunningProcessLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(barCpuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                        .addComponent(lblCpuDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                        .addComponent(lblCpuProcess)
                        .addGap(101, 101, 101))))
        );
        pnlRunningProcessLayout.setVerticalGroup(
            pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunningProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpuProcess)
                .addGap(18, 18, 18)
                .addComponent(barCpuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCpuDeadline)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlBlockedQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOCKED QUEUE (I/O)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblBlocked.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane2.setViewportView(tblBlocked);

        javax.swing.GroupLayout pnlBlockedQueueLayout = new javax.swing.GroupLayout(pnlBlockedQueue);
        pnlBlockedQueue.setLayout(pnlBlockedQueueLayout);
        pnlBlockedQueueLayout.setHorizontalGroup(
            pnlBlockedQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlockedQueueLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBlockedQueueLayout.setVerticalGroup(
            pnlBlockedQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlockedQueueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnEmergency.setBackground(new java.awt.Color(204, 0, 0));
        btnEmergency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmergency.setText("EMERGENCY INTERRUPTION");
        btnEmergency.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmergency.addActionListener(this::btnEmergencyActionPerformed);

        lblClock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClock.setText("MISSION CLOCK: CYCLE 0");

        javax.swing.GroupLayout pnlMissionControlLayout = new javax.swing.GroupLayout(pnlMissionControl);
        pnlMissionControl.setLayout(pnlMissionControlLayout);
        pnlMissionControlLayout.setHorizontalGroup(
            pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissionControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMissionControlLayout.createSequentialGroup()
                        .addComponent(pnlReadyQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMissionControlLayout.createSequentialGroup()
                                .addComponent(pnlRunningProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionControlLayout.createSequentialGroup()
                                .addComponent(btnEmergency)
                                .addGap(67, 67, 67)))
                        .addComponent(pnlBlockedQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMissionControlLayout.setVerticalGroup(
            pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissionControlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMissionControlLayout.createSequentialGroup()
                        .addComponent(pnlRunningProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnEmergency))
                    .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlBlockedQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlReadyQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("MISSION CONTROL", pnlMissionControl);

        javax.swing.GroupLayout pnlMemorySwapLayout = new javax.swing.GroupLayout(pnlMemorySwap);
        pnlMemorySwap.setLayout(pnlMemorySwapLayout);
        pnlMemorySwapLayout.setHorizontalGroup(
            pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        pnlMemorySwapLayout.setVerticalGroup(
            pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        JTabbedPanel.addTab("MEMORY & SWAP", pnlMemorySwap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPanel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyActionPerformed
        Thread interruptThread = new Thread(() -> { //Crear thread para la interrupcion
            if (kernel != null) {
                kernel.triggerEmergencyInterrupt(); //Alarma al kernel
                
                javax.swing.SwingUtilities.invokeLater(() -> { //Se fuerza a la pantalla para que 
                    refreshMissionControl();                   //se actualice y se vea el cambio
                }); 
            }
        });
        interruptThread.start();
    }//GEN-LAST:event_btnEmergencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SimulatorWindow().setVisible(true));
    }
    
    // Método para refrescar la pantalla de Mission Control
    public void refreshMissionControl() {
        if (kernel == null) return; // Evita errores si el kernel aún no ha arrancado

        javax.swing.SwingUtilities.invokeLater(() -> {
            
            //Se actualiza el CPU
            edu.unimetsim.model.PCB running = kernel.getCurrentProcess();
            if (running != null) {
                lblCpuProcess.setText(running.getName());
                barCpuProgress.setMaximum(running.getTotalInstructions()); 
                barCpuProgress.setValue(running.getTotalInstructions() - running.getRemainingTime());
                lblCpuDeadline.setText("Deadline in: " + running.getDeadline() + " cycles");
            } else {
                lblCpuProcess.setText("[IDLE - CPU Inactiva]");
                barCpuProgress.setValue(0);
                lblCpuDeadline.setText("Deadline in: -- cycles");
            }

            //Se actualiza la tabla de listos
            javax.swing.table.DefaultTableModel readyModel = (javax.swing.table.DefaultTableModel) tblReady.getModel();
            readyModel.setRowCount(0); 
            
            //Se recorre la cola nodo por nodo
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentReady = kernel.getReadyQueue().getHead();
            while (currentReady != null) {
                edu.unimetsim.model.PCB p = currentReady.getData(); 
                readyModel.addRow(new Object[]{ p.getName(), p.getPriority() });
                currentReady = currentReady.getNext(); 
            }

            //Se actualiza la tabla de bloqueados
            javax.swing.table.DefaultTableModel blockedModel = (javax.swing.table.DefaultTableModel) tblBlocked.getModel();
            blockedModel.setRowCount(0); 
            
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentBlocked = kernel.getBlockedQueue().getHead();
            while (currentBlocked != null) {
                edu.unimetsim.model.PCB p = currentBlocked.getData();
                blockedModel.addRow(new Object[]{ p.getName(), p.getPriority() });
                currentBlocked = currentBlocked.getNext();
            }
            
            //Y se actualiza el reloj
            lblClock.setText("MISSION CLOCK: Cycle " + kernel.getGlobalClock());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JProgressBar barCpuProgress;
    private javax.swing.JButton btnEmergency;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCpuDeadline;
    private javax.swing.JLabel lblCpuProcess;
    private javax.swing.JPanel pnlBlockedQueue;
    private javax.swing.JPanel pnlMemorySwap;
    private javax.swing.JPanel pnlMissionControl;
    private javax.swing.JPanel pnlReadyQueue;
    private javax.swing.JPanel pnlRunningProcess;
    private javax.swing.JTable tblBlocked;
    private javax.swing.JTable tblReady;
    // End of variables declaration//GEN-END:variables
}
