package edu.unimetsim.view;


import edu.unimetsim.model.PCB;
import edu.unimetsim.model.ProcessGenerator;
import edu.unimetsim.model.ProcessManager;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import edu.unimetsim.structures.LinkedList;
import edu.unimetsim.structures.Queue;
import edu.unimetsim.structures.Node;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pinto
 */
public class SimulatorWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimulatorWindow.class.getName());
    private ProcessManager kernel; //Para que se entienda con el PM

    
    public void setKernel(ProcessManager kernel) {
        this.kernel = kernel;
        refreshMissionControl();
    }
    /**
     * Creates new form SimulatorWindow
     */
    public SimulatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTabbedPanel = new javax.swing.JTabbedPane();
        pnlMissionControl = new javax.swing.JPanel();
        pnlReadyQueue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReady = new javax.swing.JTable();
        pnlRunningProcess = new javax.swing.JPanel();
        lblCpuProcess = new javax.swing.JLabel();
        barCpuProgress = new javax.swing.JProgressBar();
        lblCpuDeadline = new javax.swing.JLabel();
        pnlBlockedQueue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBlocked = new javax.swing.JTable();
        btnEmergency = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        stressTest = new javax.swing.JButton();
        cmbAlgorithm = new javax.swing.JComboBox<>();
        pnlMemorySwap = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        barMemoryUsage = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlReadySuspended = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReadySuspended = new javax.swing.JTable();
        pnlBlockedSuspended = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBlockedSuspended = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlReadyQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "READY QUEUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblReady.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane1.setViewportView(tblReady);

        javax.swing.GroupLayout pnlReadyQueueLayout = new javax.swing.GroupLayout(pnlReadyQueue);
        pnlReadyQueue.setLayout(pnlReadyQueueLayout);
        pnlReadyQueueLayout.setHorizontalGroup(
            pnlReadyQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReadyQueueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReadyQueueLayout.setVerticalGroup(
            pnlReadyQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadyQueueLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRunningProcess.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RUNNING PROCESS (CPU)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        lblCpuProcess.setText("NO PROCESS");

        lblCpuDeadline.setText("DEADLINE IN: -- CYCLES");

        javax.swing.GroupLayout pnlRunningProcessLayout = new javax.swing.GroupLayout(pnlRunningProcess);
        pnlRunningProcess.setLayout(pnlRunningProcessLayout);
        pnlRunningProcessLayout.setHorizontalGroup(
            pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunningProcessLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(barCpuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                        .addComponent(lblCpuDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunningProcessLayout.createSequentialGroup()
                        .addComponent(lblCpuProcess)
                        .addGap(101, 101, 101))))
        );
        pnlRunningProcessLayout.setVerticalGroup(
            pnlRunningProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunningProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpuProcess)
                .addGap(18, 18, 18)
                .addComponent(barCpuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCpuDeadline)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlBlockedQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOCKED QUEUE (I/O)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblBlocked.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane2.setViewportView(tblBlocked);

        javax.swing.GroupLayout pnlBlockedQueueLayout = new javax.swing.GroupLayout(pnlBlockedQueue);
        pnlBlockedQueue.setLayout(pnlBlockedQueueLayout);
        pnlBlockedQueueLayout.setHorizontalGroup(
            pnlBlockedQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlockedQueueLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBlockedQueueLayout.setVerticalGroup(
            pnlBlockedQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlockedQueueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnEmergency.setBackground(new java.awt.Color(204, 0, 0));
        btnEmergency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmergency.setText("EMERGENCY INTERRUPTION");
        btnEmergency.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmergency.addActionListener(this::btnEmergencyActionPerformed);

        lblClock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClock.setText("MISSION CLOCK: CYCLE 0");

        stressTest.setText("STRESS TEST");
        stressTest.addActionListener(this::stressTestActionPerformed);

        cmbAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "RR", "SRT", "EDF", "PRIORITY" }));
        cmbAlgorithm.addActionListener(this::cmbAlgorithmActionPerformed);

        javax.swing.GroupLayout pnlMissionControlLayout = new javax.swing.GroupLayout(pnlMissionControl);
        pnlMissionControl.setLayout(pnlMissionControlLayout);
        pnlMissionControlLayout.setHorizontalGroup(
            pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissionControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMissionControlLayout.createSequentialGroup()
                        .addComponent(pnlReadyQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMissionControlLayout.createSequentialGroup()
                                    .addComponent(pnlRunningProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionControlLayout.createSequentialGroup()
                                    .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbAlgorithm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(67, 67, 67)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionControlLayout.createSequentialGroup()
                                .addComponent(stressTest)
                                .addGap(110, 110, 110)))
                        .addComponent(pnlBlockedQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMissionControlLayout.setVerticalGroup(
            pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissionControlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMissionControlLayout.createSequentialGroup()
                        .addComponent(pnlRunningProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stressTest)
                        .addGap(23, 23, 23)
                        .addComponent(btnEmergency)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMissionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlBlockedQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlReadyQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("MISSION CONTROL", pnlMissionControl);

        barMemoryUsage.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        barMemoryUsage.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("MAIN MEMORY (RAM)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("MEMORY USAGE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barMemoryUsage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(barMemoryUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlReadySuspended.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "READY SUSPENDED ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblReadySuspended.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane4.setViewportView(tblReadySuspended);

        javax.swing.GroupLayout pnlReadySuspendedLayout = new javax.swing.GroupLayout(pnlReadySuspended);
        pnlReadySuspended.setLayout(pnlReadySuspendedLayout);
        pnlReadySuspendedLayout.setHorizontalGroup(
            pnlReadySuspendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadySuspendedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReadySuspendedLayout.setVerticalGroup(
            pnlReadySuspendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadySuspendedLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBlockedSuspended.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOCKED SUSPENDED", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        tblBlockedSuspended.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PROCESS", "PRIORITY"
            }
        ));
        jScrollPane5.setViewportView(tblBlockedSuspended);

        javax.swing.GroupLayout pnlBlockedSuspendedLayout = new javax.swing.GroupLayout(pnlBlockedSuspended);
        pnlBlockedSuspended.setLayout(pnlBlockedSuspendedLayout);
        pnlBlockedSuspendedLayout.setHorizontalGroup(
            pnlBlockedSuspendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlockedSuspendedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBlockedSuspendedLayout.setVerticalGroup(
            pnlBlockedSuspendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMemorySwapLayout = new javax.swing.GroupLayout(pnlMemorySwap);
        pnlMemorySwap.setLayout(pnlMemorySwapLayout);
        pnlMemorySwapLayout.setHorizontalGroup(
            pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemorySwapLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlReadySuspended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(pnlBlockedSuspended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlMemorySwapLayout.setVerticalGroup(
            pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemorySwapLayout.createSequentialGroup()
                .addGroup(pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemorySwapLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlMemorySwapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBlockedSuspended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMemorySwapLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(pnlReadySuspended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("MEMORY & SWAP", pnlMemorySwap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPanel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyActionPerformed
        Thread interruptThread = new Thread(() -> { //Crear thread para la interrupcion
            if (kernel != null) {
                kernel.triggerEmergencyInterrupt(); //Alarma al kernel
                
                javax.swing.SwingUtilities.invokeLater(() -> { //Se fuerza a la pantalla para que 
                    refreshMissionControl();                   //se actualice y se vea el cambio
                }); 
            }
        });
        interruptThread.start();
    }//GEN-LAST:event_btnEmergencyActionPerformed

    private void stressTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stressTestActionPerformed
        if (kernel != null) {
            System.out.println("\n[SISTEMA] Iniciando ingreso masivo de procesos");
            kernel.getMutex().acquire();
            
            for (int i = 0; i < 20; i++) { //los 20 procesos
                PCB newProcess = ProcessGenerator.generateRandomProcess(kernel.getGlobalClock()); 
                //Se le pasa el reloj del kernel (actual)
                // Lo enviamos al cerebro
                kernel.addProcess(newProcess);
            }
            refreshMissionControl();
            kernel.getMutex().release();
        }
    }//GEN-LAST:event_stressTestActionPerformed

    private void cmbAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgorithmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlgorithmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SimulatorWindow().setVisible(true));
    }
    
    // Método para refrescar la pantalla de Mission Control
    public void refreshMissionControl() {
        if (kernel == null) return; 

        javax.swing.SwingUtilities.invokeLater(() -> { //Para evitar que la pantalla se congele
            
            //MISION CONTROL -----------------
            //Actualizar: CPU 
            edu.unimetsim.model.PCB running = kernel.getCurrentProcess();
            if (running != null) {
                lblCpuProcess.setText(running.getName()); //Se pide el nombre del proceso que se este ejecutandp
                barCpuProgress.setMaximum(running.getTotalInstructions()); 
                barCpuProgress.setValue(running.getTotalInstructions() - running.getRemainingTime());
                lblCpuDeadline.setText("Deadline in: " + running.getDeadline() + " cycles");
            } else {
                lblCpuProcess.setText("[IDLE - CPU Inactiva]");
                barCpuProgress.setValue(0); //Se vacia la barra pq no hay nadie
                lblCpuDeadline.setText("Deadline in: -- cycles");
            }

            //Actualizar: tabla de listos (RAM)
            javax.swing.table.DefaultTableModel readyModel = (javax.swing.table.DefaultTableModel) tblReady.getModel();
            readyModel.setRowCount(0); //Borrar filas para agregar nuevas (y evitar duplicados)
            
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentReady = kernel.getReadyQueue().getHead();
            //Se usa currentReady pq si se usa dequeue se borra el proceso de la edd, cr sirve para leer la info
            while (currentReady != null) {  // y se recorre hasta llegar a null sin danar la cola
                edu.unimetsim.model.PCB p = currentReady.getData(); 
                readyModel.addRow(new Object[]{ p.getName(), p.getPriority() });
                currentReady = currentReady.getNext(); 
            }

            //Actualizar: tabla de bloqueados (RAM)
            javax.swing.table.DefaultTableModel blockedModel = (javax.swing.table.DefaultTableModel) tblBlocked.getModel();
            blockedModel.setRowCount(0); 
            
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentBlocked = kernel.getBlockedQueue().getHead();
            while (currentBlocked != null) {
                edu.unimetsim.model.PCB p = currentBlocked.getData();
                blockedModel.addRow(new Object[]{ p.getName(), p.getPriority() });
                currentBlocked = currentBlocked.getNext();
            }

            //MEMORY & SWAP -----------------
            //Actualizar: barra (RAM)
            //Total = Ready + blocked + 1 CPU (si esta ocupada) 
            int procesosEnRam = kernel.getReadyQueue().getSize() + kernel.getBlockedQueue().getSize() + (running != null ? 1 : 0);
            int capacidadMaxima = kernel.getMaxMemorySize(); 

            if (capacidadMaxima > 0) {
                int porcentaje = (int) (((double) procesosEnRam / capacidadMaxima) * 100); //double para que quede con decimales y no se redondee a 0
                barMemoryUsage.setValue(porcentaje);
                barMemoryUsage.setString("Memory Usage: " + porcentaje + "% (" + procesosEnRam + "/" + capacidadMaxima + ")");
            }

            //Actualizar: tabla ready-suspended (SWAP del DISCO)
            //tabla de los que no cupieron en la RAM y esperan en el disco
            javax.swing.table.DefaultTableModel rsModel = (javax.swing.table.DefaultTableModel) tblReadySuspended.getModel();
            rsModel.setRowCount(0);
            
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentRS = kernel.getQueueReadySuspended().getHead();
            while (currentRS != null) {
                edu.unimetsim.model.PCB p = currentRS.getData();
                rsModel.addRow(new Object[]{ p.getName(), p.getStatus(), p.getPriority(), p.getDeadline() });
                currentRS = currentRS.getNext();
            }

            //Actualizar: blocked-suspended (DISCO)
            //Procesos que estaban en RAM, se bloquearon, y los expulsaron al disco por falta de espacio
            javax.swing.table.DefaultTableModel bsModel = (javax.swing.table.DefaultTableModel) tblBlockedSuspended.getModel();
            bsModel.setRowCount(0);
            
            edu.unimetsim.structures.Node<edu.unimetsim.model.PCB> currentBS = kernel.getBlockedSuspendedQueue().getHead();
            while (currentBS != null) {
                edu.unimetsim.model.PCB p = currentBS.getData();
                bsModel.addRow(new Object[]{ p.getName(), p.getStatus(), p.getPriority(), p.getDeadline() });
                currentBS = currentBS.getNext();
            }

            //RELOJ  -----------------
            lblClock.setText("MISSION CLOCK: Cycle " + kernel.getGlobalClock());
        }); //Se actualiza
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JProgressBar barCpuProgress;
    private javax.swing.JProgressBar barMemoryUsage;
    private javax.swing.JButton btnEmergency;
    private javax.swing.JComboBox<String> cmbAlgorithm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCpuDeadline;
    private javax.swing.JLabel lblCpuProcess;
    private javax.swing.JPanel pnlBlockedQueue;
    private javax.swing.JPanel pnlBlockedSuspended;
    private javax.swing.JPanel pnlMemorySwap;
    private javax.swing.JPanel pnlMissionControl;
    private javax.swing.JPanel pnlReadyQueue;
    private javax.swing.JPanel pnlReadySuspended;
    private javax.swing.JPanel pnlRunningProcess;
    private javax.swing.JButton stressTest;
    private javax.swing.JTable tblBlocked;
    private javax.swing.JTable tblBlockedSuspended;
    private javax.swing.JTable tblReady;
    private javax.swing.JTable tblReadySuspended;
    // End of variables declaration//GEN-END:variables
}
